# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a95e15182a4adf26d7a3289d9ef8eae78fef2456a61255a125286df5a9620d9f20fd748335d4315699f21a9385f243d395890d495144d085f881e255ee331b7b

test:
  secret_key_base: b478bb7650ad54a0abcf11e53d40f7bf91f2328d216dc78492488ea95bbf6f97ca547125c873fe405b40c4c783edeeceb48a1d20a3df4d802053cb4f03e25dbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
